import type { ScenarioGraph } from "./types"
import { planToGraph, type WizardPlan } from "./wizard-plan"

// OPERATIE POLDER-STORM — starter scenario for Eye Security's tabletop trainings.
//
// Target: Dutch MKB+ org (~250 employees, essential entity under NIS2). Attack:
// ransomware + data exfiltration. Five rounds spanning ~72 hours in narrative
// time. All 8 playable roles get meaningful choices in every round. Two
// melding-moments across the scenario (IR-retainer + AP-melding). Escalation
// arc R1 → R5: ambiguous signals → confirmation → media + regulator → ransom
// decision → aftermath.
//
// This is a *starter*. Facilitators should tweak it via the builder for each
// client engagement — or generate a tailored variant with the AI wizard.

const plan: WizardPlan = {
  name: "★ OPERATIE POLDER-STORM — Ransomware + Exfil (NIS2 essential entity)",
  scenarioType: "ransomware_double_extortion",
  irPlaybook: `## Crisis playbook — Klantorganisatie

**Ransomware- en data-incident: eerste 4 uur**

1. Isoleer verdacht endpoint. **Niet uitzetten** — vluchtige data eerst.
2. Neem contact op met Eye Security via +31 (0)88 6600 700. SLA eerste contact: 15 minuten.
3. Board informeren binnen 1 uur.
4. Interne comms binnen 4 uur: medewerkers krijgen richtlijn.
5. Klanten pas informeren nadat impact is vastgesteld.

**Meldplicht**
- AVG (Autoriteit Persoonsgegevens): binnen 72 uur als persoonsgegevens betrokken.
- NIS2 (NCSC): vroegtijdige waarschuwing binnen 24 uur, volledige melding binnen 72 uur.

**Losgeld**
- Beleid: geen betaling zonder board-approval. Verzekeraar betrekken vóór onderhandeling.
- (OPZET-VEROUDERD: playbook v1 stelt "tot 50k EUR autoriseren CFO alleen" — sinds 2024 alleen board-approval, playbook nog niet bijgewerkt.)`,
  rounds: [
    // ── R1 — Ambigue signalen ──────────────────────────────────
    {
      title: "R1 — Ongewone data-egress",
      situation: "Nacht van dinsdag op woensdag, 03:47. Het MDR-team van Eye Security signaleert ongewone uitgaande verbindingen vanaf een file server naar drie onbekende IP-adressen — ongeveer 6 GB in de laatste 30 minuten. De SOC-analist belt de dienstdoende IT-manager. Het is nog onduidelijk of er iets kritisch gebeurt of dat een geplande backup abusievelijk over het productienetwerk loopt.",
      timerMinutes: 15,
      openingPrompts: [
        "Wat weten we zeker en wat is aanname?",
        "Wie is beslissingsbevoegd op dit moment?",
        "Welke klok tikt al?",
      ],
      facilitatorPerspective: "Als IR-consultant zou ik direct de retainer activeren en het endpoint isoleren voordat we méér weten. Vroege isolatie beperkt lateral spread. Let op teams die eerst 'meer feiten' willen verzamelen — te lang wachten kost containment.",
      injects: [
        {
          id: "r1-siem",
          type: "alert", channel: "siem", urgency: "critical",
          title: "MDR-alert — Ongewone data-egress",
          content: "6.4 GB uitgaand naar 3 IPs (2 in RU, 1 in NL VPS-hoster) in 30 min. Bron: FS-PROD-01. Betrokken share: /finance/klantcontracten.",
          reliability: "fact",
          senderName: "SOC — Eye Security", timestamp: "03:47",
          targetTeam: "technical_it",
        },
        {
          id: "r1-whatsapp",
          type: "internal", channel: "whatsapp", urgency: "low",
          title: "WhatsApp van collega",
          content: "Ff kort — was jullie backup gepland vannacht? Klinkt als een test. Meld ik het aan Piet of laten we het lopen?",
          reliability: "misleading",
          senderName: "IT-collega Marijn", timestamp: "03:52",
          deliverySeconds: 90,
          targetTeam: "technical_it",
        },
      ],
      meldingMoment: {
        id: "r1-melding-retainer",
        allowedRoles: ["ceo", "ciso", "it_manager"],
        recipient: "ir_retainer",
        helper: "Bij twijfel: Eye Security bellen. SLA eerste contact 15 min.",
        types: [
          { id: "activate-retainer", label: "Eye Security-retainer activeren", triggersInjectId: "r1-retainer-response" },
        ],
      },
      roleActions: [
        {
          id: "r1-ceo-authorize", label: "Autoriseer noodmaatregelen",
          description: "Geef de CISO expliciet mandaat voor onmiddellijke containment-beslissingen.",
          allowedRoles: ["ceo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Vroeg mandaat geven werkt goed — team weet dat de CISO mag handelen zonder verdere goedkeuring.",
          lessonLearned: "Mandaatduidelijkheid: één iemand mag beslissen zolang de feiten kloppen.",
        },
        {
          id: "r1-ceo-wait", label: "Wacht op meer feiten",
          description: "Vraag CISO om binnen 30 min meer info voordat maatregelen worden getroffen.",
          allowedRoles: ["ceo"], irPlanAligned: false,
          qualityRank: "poor",
          facilitatorCommentary: "Wachten zonder deadline is duur — lateral spread kost containment.",
          lessonLearned: "Actie onder onzekerheid is soms beter dan wachten op zekerheid.",
        },
        {
          id: "r1-ciso-isolate", label: "Isoleer FS-PROD-01 direct",
          description: "Zet de file server netwerktechnisch offline. Log en image behouden.",
          allowedRoles: ["ciso"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Snelle isolatie, forensische positie behouden. Textbook.",
          lessonLearned: "Isoleren ≠ uitzetten. Vluchtige data blijft beschikbaar.",
        },
        {
          id: "r1-it-shutdown", label: "Zet de file server uit",
          description: "Trek de stekker. Snelste containment, maar RAM verdwijnt.",
          allowedRoles: ["it_manager", "ciso"], irPlanAligned: false,
          qualityRank: "poor", respondsToMisleading: false,
          facilitatorCommentary: "Uitschakelen wist bewijs. Isolatie via netwerk was de betere keuze.",
          lessonLearned: "Forensische impact van 'quick fix': bewijs kwijt.",
        },
        {
          id: "r1-it-followmarijn", label: "Bel Marijn, check of het een test is",
          description: "Reageer op de WhatsApp — misschien is dit inderdaad geplande backup.",
          allowedRoles: ["it_manager"], irPlanAligned: false,
          qualityRank: "wrong", respondsToMisleading: true,
          facilitatorCommentary: "Klassieke BOB-vergissing: aanname als feit. Marijn's WhatsApp is geen SOC-verificatie.",
          lessonLearned: "Signalen vaststellen bij de bron, niet via collega's.",
        },
        {
          id: "r1-legal-clock", label: "Start de meldplicht-klok",
          description: "Log het tijdstip van eerste detectie. Bereid AVG/NIS2-melding voor als het bevestigd wordt.",
          allowedRoles: ["legal"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Vroeg de klok starten. AVG art. 33 en NIS2 art. 23 kennen geen 'we wisten het nog niet zeker'.",
          lessonLearned: "Meldplicht start bij detectie, niet bij bevestiging.",
        },
        {
          id: "r1-cfo-insurer", label: "Verzekeraar preventief informeren",
          description: "Meld het incident bij de cyberverzekeraar. Zonder tijdige melding vervalt dekking.",
          allowedRoles: ["cfo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Meeste polissen vereisen melding binnen 24-72 uur na detectie.",
          lessonLearned: "Verzekering activeren voordat je er iets van wilt.",
        },
        {
          id: "r1-comms-monitor", label: "Monitor kanalen op eerste ruis",
          description: "Zet monitoring op social media / pers. Bereid holding statement voor.",
          allowedRoles: ["head_of_comms"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Vroegtijdig statement klaarzetten geeft je de regie als het uitkomt.",
          lessonLearned: "Communicatie voorbereiden ≠ communiceren.",
        },
        {
          id: "r1-hr-standby", label: "Zet HR-crisisdraaiboek op stand-by",
          description: "Prepare medewerkerscommunicatie. Nog niet verzenden.",
          allowedRoles: ["hr_lead"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Medewerkers moeten van jou horen, niet van de media.",
          lessonLearned: "Intern voor extern.",
        },
        {
          id: "r1-ops-inventory", label: "Inventariseer afhankelijkheden FS-PROD-01",
          description: "Welke processen leunen op deze server? BC-impact van isolatie.",
          allowedRoles: ["ops_manager"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Zonder deze inventarisatie besluit de CISO in het duister over de BC-cost van isoleren.",
          lessonLearned: "Trade-off containment ↔ continuïteit is alleen te maken met impact-data.",
        },
      ],
      discussionGoal: "Test of het team feiten en aannames scheidt vóór actie, en of mandaten helder zijn.",
      keyQuestions: [
        "Welke informatie is feit en welke is aanname?",
        "Wie is nú beslissingsbevoegd?",
        "Welke meldplicht-klok tikt al?",
      ],
      hints: ["Kijk wie de WhatsApp serieus neemt als feit."],
      expectedDecisions: ["IR-retainer activeren", "Isoleren via netwerk", "Meldplicht-klok starten"],
      redFlags: ["Team wacht op 'meer feiten' zonder deadline", "Uitschakelen ipv isoleren"],
    },
    // ── R2 — Bevestiging + ransom-note ──────────────────────────
    {
      title: "R2 — Ransom-note en encrypted shares",
      situation: "Woensdag 06:15. Meerdere medewerkers melden dat file shares niet toegankelijk zijn. Op de share /finance staat een ransom-note (BlackCat/ALPHV-variant): 'We have exfiltrated 6.4 GB including client contracts. Pay 800.000 EUR in BTC within 72 hours or we publish.' De pers krijgt lucht van iets — TechCrunch NL vraagt bevestiging.",
      timerMinutes: 15,
      openingPrompts: [
        "Wat is de kritieke keten van deze 72u?",
        "Wie heeft mandaat over losgeld-beslissing?",
        "Zijn kroonjuwelen bevestigd getroffen?",
      ],
      facilitatorPerspective: "Nu wordt het echt. Focus: 1) meldplicht-triage, 2) intern communiceren vóór media eruit is, 3) NIET onderhandelen zonder verzekeraar. Let op teams die willen betalen 'om ervan af te zijn'.",
      injects: [
        {
          id: "r2-ransom",
          type: "intel", channel: "ransom_note", urgency: "critical",
          title: "Ransom-note (BlackCat)",
          content: "TO WHOM IT MAY CONCERN — We have 6.4 GB of your data including /finance/klantcontracten and internal e-mail archives. Pay 800.000 EUR in BTC within 72h to wallet [redacted]. Non-payment = full publication on our leaksite. Any negotiation attempt: multiplier +50%.",
          reliability: "fact",
          senderName: "BlackCat / ALPHV", timestamp: "06:15",
        },
        {
          id: "r2-media",
          type: "media", channel: "news", urgency: "high",
          title: "TechCrunch NL — vraagt bevestiging",
          content: "Anonieme bron meldt dat er 'iets aan de hand is' bij uw organisatie. Kunt u bevestigen of ontkennen dat er sprake is van een cyberincident? Deadline reactie: 09:00.",
          reliability: "fact",
          senderName: "Redactie TechCrunch NL", timestamp: "06:41",
          deliverySeconds: 120,
        },
        {
          id: "r2-employee",
          type: "internal", channel: "email", urgency: "medium",
          title: "Medewerker: 'Ik kan niet werken'",
          content: "Beste HR, ik kan de klant-contracten niet openen. Kan ik werken van huis of komen we in de problemen? Ik hoor van een collega dat er iets speelt maar niemand weet wat.",
          reliability: "fact",
          senderName: "Account Manager L.", timestamp: "07:03",
        },
      ],
      roleActions: [
        {
          id: "r2-ceo-boardbrief", label: "Directie/RvC formeel informeren",
          description: "Belangrijkste stakeholders van dit incident geïnformeerd. Vraag om board-approval voor losgeld-scenario.",
          allowedRoles: ["ceo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Board pre-approven voordat je in de losgeld-onderhandeling stapt is verstandig.",
          lessonLearned: "Governance: board formeel informeren binnen 4h.",
        },
        {
          id: "r2-ceo-decide-pay", label: "Beslis nu al: we gaan betalen",
          description: "Autoriseer de CFO om onderhandeling met de aanvaller te starten.",
          allowedRoles: ["ceo"], irPlanAligned: false,
          qualityRank: "wrong",
          facilitatorCommentary: "Betaling zonder herstelkans-check + zonder verzekeraar = KOS -2, JUR -1.",
          lessonLearned: "Betaling is een LAATSTE optie — pas na verkenning van herstel.",
        },
        {
          id: "r2-ciso-scope", label: "Bepaal scope: welke servers nog meer?",
          description: "Forensisch onderzoek: kruipt de aanvaller ergens anders?",
          allowedRoles: ["ciso"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Zonder scope-check is elk herstel prematuur.",
          lessonLearned: "Herstellen zonder scope = terug bij af binnen dagen.",
        },
        {
          id: "r2-it-restore", label: "Start herstel van backups",
          description: "Probeer laatste backup van FS-PROD-01 terug te zetten.",
          allowedRoles: ["it_manager"], irPlanAligned: false,
          qualityRank: "poor",
          facilitatorCommentary: "Herstellen zonder scope-check kan de aanvaller opnieuw binnenlaten via een andere ingang.",
          lessonLearned: "Backup restore zonder attack-scope = quick fix die vaak weer breekt.",
        },
        {
          id: "r2-legal-notify72", label: "AVG-melding aan AP voorbereiden",
          description: "Klantcontracten bevatten persoonsgegevens. 72u-klok tikt sinds 03:47.",
          allowedRoles: ["legal"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "AVG art. 33 verplicht binnen 72u — reken terug vanaf detectie, niet vanaf ransom-note.",
          lessonLearned: "72u-klok start bij detectie.",
        },
        {
          id: "r2-legal-ncsc24", label: "NCSC vroegtijdige waarschuwing indienen",
          description: "NIS2 art. 23 lid 4a: 'early warning' binnen 24u. Klok tikt.",
          allowedRoles: ["legal"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Vaak vergeten — de 24u NCSC-melding is aparte klok naast de 72u AP-melding.",
          lessonLearned: "Twee klokken tegelijk: NCSC 24u, AP 72u.",
        },
        {
          id: "r2-cfo-verzekeraar", label: "Verzekeraar activeren + onderhandelaar aanvragen",
          description: "Meeste polissen dekken een gespecialiseerde onderhandelaar.",
          allowedRoles: ["cfo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Verzekeraar heeft een netwerk aan onderhandelaars die dit dagelijks doen.",
          lessonLearned: "Nooit zelf onderhandelen met een gedreven ransomware-actor.",
        },
        {
          id: "r2-comms-hold", label: "Holding-statement uitgeven",
          description: "Publiek statement: 'Wij zijn op de hoogte, onderzoek loopt, meer info volgt.' Klopt met feiten, geeft je tijd.",
          allowedRoles: ["head_of_comms"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Holding-statement is het VER-instrument bij uitstek. Tijd kopen zonder liegen.",
          lessonLearned: "Communicatie-regie behouden door vroege holding statement.",
        },
        {
          id: "r2-comms-deny", label: "Ontken tegen TechCrunch",
          description: "Zeg dat er niets aan de hand is en dat verstoringen 'routineonderhoud' zijn.",
          allowedRoles: ["head_of_comms", "ceo"], irPlanAligned: false,
          qualityRank: "wrong",
          facilitatorCommentary: "Liegen tegen pers = wanneer het uitkomt is de reputatieschade dubbel.",
          lessonLearned: "VER-dimensie: transparantie wint van korte-termijn geruststelling.",
        },
        {
          id: "r2-hr-internal", label: "Interne update naar alle medewerkers",
          description: "1-pagina uitleg: wat er is, wat het betekent voor werk, wanneer volgende update.",
          allowedRoles: ["hr_lead"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Voor 09:00 versturen — anders horen ze het van TechCrunch.",
          lessonLearned: "Interne communicatie: eerste 4 uur cruciaal.",
        },
        {
          id: "r2-ops-workaround", label: "Activeer noodprocedures voor klantorders",
          description: "Handmatige orderintake, backup-shared drive op laptops. BC-continuïteit voor klanten.",
          allowedRoles: ["ops_manager"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Klanten merken pas iets als je BC-workaround faalt. Vroeg activeren.",
          lessonLearned: "Noodprocedures op paper zijn niets waard zonder tests.",
        },
      ],
      discussionGoal: "Test of het team de twee meldplicht-klokken herkent en of comms-regie behouden blijft.",
      keyQuestions: [
        "Betaal je losgeld ja/nee — hoe beslis je dat?",
        "Wanneer moet welke melding eruit?",
        "Wat vertellen we medewerkers en wanneer?",
      ],
      hints: ["Let op teams die 'even later' antwoord geven op TechCrunch."],
      expectedDecisions: ["AVG-melding voorbereid", "NCSC 24u-melding", "Verzekeraar geactiveerd", "Holding statement"],
      redFlags: ["Beslissing over losgeld zonder board + verzekeraar", "Ontkennen richting pers"],
    },
    // ── R3 — Meldplicht-fase + AP-melding ──────────────────────
    {
      title: "R3 — Autoriteit Persoonsgegevens + media",
      situation: "Donderdag 10:30 — 30 uur na detectie. TechCrunch NL heeft gisteren om 15:00 gepubliceerd. Klanten bellen. De AP heeft in een generieke uiting laten weten 'op de hoogte' te zijn van signalen. Bevestigd is inmiddels: 6.4 GB uitgelekt, waarvan ~250 MB persoonsgegevens (contracten, financiële klantdata). Ransom-timer: 42 uur.",
      timerMinutes: 15,
      openingPrompts: [
        "Wat is de status van jullie meldingen NCSC + AP?",
        "Hoe lopen jullie klant-communicatie en pers-communicatie synchroon?",
        "Wat is de herstel-inschatting van IT/CISO?",
      ],
      facilitatorPerspective: "R3 test compliance-executie. AP-melding moet nu écht klaar zijn — 72u-klok loopt tot vrijdag 03:47. Let op teams die 'nog wachten op meer info' — dat werkt niet meer.",
      injects: [
        {
          id: "r3-ap-inbox",
          type: "regulatory", channel: "email", urgency: "high",
          title: "AP — Datalekmelding ontvangst",
          content: "Uw datalekmelding is in behandeling genomen. Casusnummer AP-2024-XXXXX. Aanvullende vragen volgen. Op basis van de melding kan aanvullende informatievoorziening aan betrokkenen vereist zijn (AVG art. 34).",
          reliability: "fact",
          senderName: "Autoriteit Persoonsgegevens", timestamp: "10:30",
        },
        {
          id: "r3-customer-call",
          type: "executive", channel: "phone", urgency: "high",
          title: "Grote klant belt CEO",
          content: "Beste [CEO], ik lees in TechCrunch dat jullie een cyberincident hebben. Betekent dit dat OUZE contracten zijn uitgelekt? Ik moet dit vandaag bij mijn eigen board bespreken. Kunt u me om 14:00 concreet informeren?",
          reliability: "fact",
          senderName: "CFO Klant Zeeland-Ondernemer BV", timestamp: "11:12",
        },
        {
          id: "r3-hr-plants-rumor",
          type: "internal", channel: "whatsapp", urgency: "medium",
          title: "Interne roddel op WhatsApp",
          content: "Iemand in het OR-groepschatje: 'Ik heb gehoord dat de directie al €800k heeft betaald. Waarom horen wij dat niet? Zit ons pensioen ook in de leak?'",
          reliability: "misleading",
          senderName: "OR-lid (leaked)", timestamp: "11:44",
        },
      ],
      meldingMoment: {
        id: "r3-melding-ap",
        allowedRoles: ["legal", "ceo"],
        recipient: "ap",
        helper: "AVG art. 33: 72u voor melding aan AP. Klok tikt sinds 03:47 dinsdagnacht.",
        types: [
          { id: "ap-melding-volledig", label: "Volledige AVG-melding indienen bij AP", triggersInjectId: "r3-followup-ap" },
        ],
      },
      roleActions: [
        {
          id: "r3-ceo-customercall", label: "Bel klant persoonlijk terug — feiten zonder speculatie",
          description: "Persoonlijk contact + eerlijke stand van zaken + afspraak wanneer meer info volgt.",
          allowedRoles: ["ceo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Klantrelaties overleven eerlijkheid. Vaagheid doodt ze.",
          lessonLearned: "In VER-dimensie: transparantie tegen klanten is kritiek.",
        },
        {
          id: "r3-ceo-delegate", label: "Delegeer klantcommunicatie aan account manager",
          description: "Laat de accountmanager het gesprek voeren volgens template.",
          allowedRoles: ["ceo"], irPlanAligned: false,
          qualityRank: "poor",
          facilitatorCommentary: "Van deze omvang verwacht een klant CEO-contact.",
          lessonLearned: "Positioneel: welke crisis vraagt CEO-face-time?",
        },
        {
          id: "r3-ciso-forensic", label: "Forensisch rapport voor AP-melding opstellen",
          description: "Concrete cijfers: welke data, hoe uitgelekt, welke logs bewijzen wat.",
          allowedRoles: ["ciso"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "AP is niet tevreden met vage samenvattingen. Concrete data = betere positie.",
          lessonLearned: "Forensische afhandeling is compliance-input.",
        },
        {
          id: "r3-it-restore-priorities", label: "Herstelplan met prioriteiten opstellen",
          description: "Welke systemen eerst? Impact ↔ herstelkans matrix.",
          allowedRoles: ["it_manager"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Herstel = business-beslissing met IT als adviseur. Ops betrekken.",
          lessonLearned: "Prioriteiten voor herstel liggen bij ops, niet IT.",
        },
        {
          id: "r3-legal-ap-formal", label: "AVG-melding formeel indienen bij AP",
          description: "Vandaag vóór 15:00. Alle bijlages, IOCs, impact-inschatting.",
          allowedRoles: ["legal"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "AVG art. 33: 72u-klok tikt sinds 03:47 dinsdag → moet vandaag eruit.",
          lessonLearned: "Meldplicht is niet 'binnen 72u proberen' — het is 'moet klaar zijn'.",
        },
        {
          id: "r3-legal-datasubjects", label: "Betrokkenen (klanten) informeren voorbereiden",
          description: "AVG art. 34: bij hoog risico moeten betrokkenen individueel worden geïnformeerd.",
          allowedRoles: ["legal"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Vaak vergeten — na AP-melding volgt vaak verplichting individuen te informeren.",
          lessonLearned: "AP-melding ≠ eindpunt van meldplicht.",
        },
        {
          id: "r3-cfo-decision-pay", label: "Losgeld-scenario met verzekeraar doorrekenen",
          description: "Verzekeraars-onderhandelaar heeft naar 400k afgepingeld. Board approval?",
          allowedRoles: ["cfo"], irPlanAligned: true,
          qualityRank: "good",
          facilitatorCommentary: "Board-approval → onderhandelen ≠ betalen. Onderhandelen kan uitstel geven.",
          lessonLearned: "Onderhandeling ≠ toezegging.",
        },
        {
          id: "r3-comms-update", label: "Publieke update: wat we weten, wat we doen",
          description: "Transparante update via persbericht en site. Timeline, mitigaties, contact voor betrokkenen.",
          allowedRoles: ["head_of_comms"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Duidelijkheid is nu belangrijker dan volledigheid.",
          lessonLearned: "Op elk kritiek moment: iets zeggen > niets zeggen.",
        },
        {
          id: "r3-hr-rumors", label: "OR-roddel actief tegenspreken met feiten",
          description: "OR-voorzitter bellen. Feit: er is niet betaald. Feit: pensioendata zit NIET in de leak.",
          allowedRoles: ["hr_lead"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Interne roddel wordt binnen 24u externe pers. Snel corrigeren.",
          lessonLearned: "Intern vertrouwen = extern vertrouwen.",
        },
        {
          id: "r3-ops-bc-continue", label: "BC-workaround naar dag 3 verlengen",
          description: "Handmatige processen 48u vasthouden. Klanten geïnformeerd over vertraging.",
          allowedRoles: ["ops_manager"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "BC = uithoudingsvermogen. Niet elke crisis is voorbij binnen 24u.",
          lessonLearned: "BC-workarounds moeten dagen kunnen duren.",
        },
      ],
      discussionGoal: "Test compliance-executie en of comms consistent blijft over kanalen heen.",
      keyQuestions: [
        "AP-melding: gaat die vóór 15:00 eruit?",
        "Wat vertellen we betrokkenen (AVG 34)?",
        "Blijven interne en externe verhaal consistent?",
      ],
      hints: ["Let op wie de OR-roddel serieus neemt of afdoet."],
      expectedDecisions: ["AP-melding ingediend", "Klant persoonlijk geïnformeerd", "OR-roddel gecorrigeerd"],
      redFlags: ["AP-melding niet af binnen 72u", "Vage klantcommunicatie", "Roddel genegeerd"],
    },
    // ── R4 — Losgeld-beslissing ───────────────────────────────
    {
      title: "R4 — Ransom-deadline nadert",
      situation: "Vrijdag 08:00 — 52 uur na detectie. Ransom-timer nog 20 uur. Verzekeraars-onderhandelaar meldt: aanvaller staat 'stevig' op 800k EUR, maar 500k EUR is haalbaar. Herstel via backups blijkt gedeeltelijk mogelijk — 70% van kritieke data terug te halen, maar klantcontracten laatste 3 weken zijn weg. Board vraagt om een concreet voorstel binnen 4 uur.",
      timerMinutes: 15,
      openingPrompts: [
        "Betalen of niet — op basis waarvan besluit je?",
        "Wat is de reputatie-impact van elk pad?",
        "Wat zegt jullie interne beleid + verzekeringspolis?",
      ],
      facilitatorPerspective: "Dit is de zwaarste ronde. Let op teams die 'gewoon betalen' — de correcte beslissing is scenario-afhankelijk, maar het proces moet altijd: (1) restore-kans schatten, (2) verzekeraar consulteren, (3) juridische risico's op sancties (OFAC etc.), (4) board approven.",
      injects: [
        {
          id: "r4-neg",
          type: "intel", channel: "email", urgency: "critical",
          title: "Onderhandelaar — status",
          content: "We hebben 500k EUR als bovengrens. Aanvaller reageert traag. Als jullie beslissen te betalen: max 500k EUR, met bewijs van deletion + geen leaksite = voorwaarden. Herstel-parallel: probeer backup-terugzet, kan mislukken door corruptie in schaduw-backup.",
          reliability: "fact",
          senderName: "Cyber-onderhandelaar (via verzekeraar)", timestamp: "08:12",
        },
        {
          id: "r4-restore-partial",
          type: "technical", channel: "email", urgency: "high",
          title: "IT — backup-restore testresultaat",
          content: "70% van kritieke shares hersteld via offsite backup van vrijdag oud. Klantcontracten laatste 3 weken NIET aanwezig (waren nog niet gebackupt). Herstel-tijd: ~36u. Aanvaller mogelijk nog niet volledig uit netwerk — extra sweep vereist.",
          reliability: "fact",
          senderName: "IT-manager", timestamp: "08:33",
        },
        {
          id: "r4-partner-worry",
          type: "executive", channel: "email", urgency: "medium",
          title: "Ketenpartner — bezorgd",
          content: "We krijgen signalen dat jullie incident onze processen kan raken. Onze compliance-officer vraagt om schriftelijke bevestiging dat onze klantdata NIET in de exfil zit.",
          reliability: "fact",
          senderName: "Ketenpartner Van der Bergh", timestamp: "09:01",
        },
      ],
      roleActions: [
        {
          id: "r4-ceo-decide-nopay", label: "Beslis: NIET betalen — herstellen via backups",
          description: "Accepteer verlies laatste 3 weken. Handhaaf 'geen losgeld'-principe.",
          allowedRoles: ["ceo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Principe-standhouden werkt lang niet altijd — maar als je het doet moet je BC-alternatief solide zijn.",
          lessonLearned: "Niet-betalen alleen verantwoord als herstel-plan solide is.",
        },
        {
          id: "r4-ceo-decide-pay", label: "Beslis: WEL betalen — 500k via verzekeraar",
          description: "Betaling om leak te voorkomen; risico op recidive geaccepteerd.",
          allowedRoles: ["ceo"], irPlanAligned: true,
          qualityRank: "poor",
          facilitatorCommentary: "Betalen is soms defensibel — maar reputatie-effect blijft: 'zij betaalden'.",
          lessonLearned: "Losgeld betaalt geen zekerheid — 30% recidive-kans binnen 6 maanden.",
        },
        {
          id: "r4-ceo-postpone", label: "Beslis: uitstel — laat onderhandelaar 24u rekken",
          description: "Deadline aanvaller verlengen; ondertussen herstel voortzetten.",
          allowedRoles: ["ceo"], irPlanAligned: true,
          qualityRank: "good",
          facilitatorCommentary: "Uitstel is een strategie zolang je niet in slaap valt. Elke uur = restore vordert.",
          lessonLearned: "Tijd kopen is waarde als je die tijd gebruikt.",
        },
        {
          id: "r4-ciso-sweep", label: "Volledige netwerk-sweep vóór restore",
          description: "Zorg dat de aanvaller definitief weg is voordat je systemen aanzet.",
          allowedRoles: ["ciso"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Restoren zonder sweep = week 2 een nieuwe crisis.",
          lessonLearned: "Attack-eradication vóór restore. Altijd.",
        },
        {
          id: "r4-it-restore", label: "Start restore-procedure 70% shares",
          description: "Terugzetten naar productie na sweep-check.",
          allowedRoles: ["it_manager"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Feitelijk werk. Documenteren voor forensisch rapport.",
          lessonLearned: "Restore-timeline is BC-signaal aan klanten.",
        },
        {
          id: "r4-legal-partner", label: "Ketenpartner: schriftelijke response",
          description: "Bevestig welke data wel/niet in de exfil zit. Contractuele verplichting.",
          allowedRoles: ["legal"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Ketenpartner-communicatie is contractueel. Vaak vergeten en dan komt boete.",
          lessonLearned: "B2B-contracten hebben notificatie-clauses.",
        },
        {
          id: "r4-cfo-insurance-claim", label: "Formele verzekeringsclaim indienen",
          description: "Alle documentatie compleet: incident-log, kosten, betalingsvoorstel (indien).",
          allowedRoles: ["cfo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Claim moet feitelijk en compleet. Achteraf aanvullen is moeilijk.",
          lessonLearned: "Verzekering claimen is een discipline op zich.",
        },
        {
          id: "r4-comms-decisionprep", label: "Communicatie-plan voor betaalbesluit klaarzetten",
          description: "Twee versies: 'wij betalen niet' + 'wij hebben betaald'. Klaar om te draaien.",
          allowedRoles: ["head_of_comms"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Beide narratieven voorbereiden. Klantvertrouwen wordt hier gemaakt of gebroken.",
          lessonLearned: "Communicatie parallel aan besluit voorbereiden.",
        },
        {
          id: "r4-hr-employeeimpact", label: "Medewerkers-impact update",
          description: "Betekent dit ontslag? Bonus-uitstel? Boodschap onder Q&A-format.",
          allowedRoles: ["hr_lead"], irPlanAligned: true, isRecommended: true,
          qualityRank: "good",
          facilitatorCommentary: "Medewerkers denken 'wat betekent dit voor MIJ'. Adresseer dat.",
          lessonLearned: "Interne comms: WIIFM — What's In It For Me.",
        },
        {
          id: "r4-ops-partial-run", label: "Partial-productie plan naast herstel",
          description: "Wat KAN doorwerken zonder gehele restore? Prio-klanten eerst.",
          allowedRoles: ["ops_manager"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Ops-prioritering laat zien wie strategisch prioriteert onder druk.",
          lessonLearned: "80/20 tijdens crisis: welke 20% klanten mag NIET verstoord?",
        },
      ],
      discussionGoal: "Test besluitvormingsproces onder ambiguïteit — team moet expliciete criteria hebben.",
      keyQuestions: [
        "Op basis waarvan besluit je pay/no-pay?",
        "Kan je herstel-plan de deadline halen?",
        "Wat zeg je tegen de ketenpartner?",
      ],
      hints: ["Let op wie criteria expliciet maakt vs wie op onderbuik beslist."],
      expectedDecisions: ["Duidelijk pay/no-pay besluit met rationale", "Herstel-plan met sweep", "Ketenpartner geïnformeerd"],
      redFlags: ["'Even betalen om ervan af te zijn'", "Restore zonder sweep", "Ketenpartner vergeten"],
    },
    // ── R5 — Post-crisis + lessen ─────────────────────────────
    {
      title: "R5 — Post-crisis debrief",
      situation: "Maandag 09:00 — drie werkdagen na detectie. Herstel is voltooid tot 92%. Er is geen betaling gedaan (of wel, afhankelijk van R4). Aanvaller heeft (of niet) klantdata gepubliceerd. AP-onderzoek loopt. Media-belangstelling verwatert. Nu: hoe verankeren we de lessen — en welke governance-verandering volgt?",
      timerMinutes: 15,
      openingPrompts: [
        "Welke drie beslissingen achteraf zou je anders doen?",
        "Wat mist er in jullie playbook?",
        "Wie moet welke oorzaak-aanpakken?",
      ],
      facilitatorPerspective: "R5 is meestal het zwakst gefaciliteerd — teams zijn moe. Toch is dit waar veranderingen worden vastgelegd of niet. Focus op concreet: wat verandert er maandag in het IR-plan?",
      injects: [
        {
          id: "r5-ap-inspection",
          type: "regulatory", channel: "email", urgency: "high",
          title: "AP — Aankondiging vervolgonderzoek",
          content: "Op basis van uw melding en berichtgeving in media start de AP een vervolgonderzoek naar naleving AVG art. 32 (technische beveiliging). Antwoorden op vragenlijst binnen 14 dagen.",
          reliability: "fact",
          senderName: "Autoriteit Persoonsgegevens", timestamp: "09:00",
        },
        {
          id: "r5-board-question",
          type: "executive", channel: "email", urgency: "medium",
          title: "RvC — vragen voor evaluatie",
          content: "Voor de RvC-vergadering woensdag: (1) waarom ontdekten wij pas na 6 uur? (2) waarom stond FS-PROD-01 niet in MDR-scope? (3) welk budget vereist het volgende niveau? Antwoord vóór dinsdagavond.",
          reliability: "fact",
          senderName: "Voorzitter RvC", timestamp: "09:33",
        },
        {
          id: "r5-employee-thank",
          type: "internal", channel: "email", urgency: "low",
          title: "Medewerker bedankt team",
          content: "Ik wil complimenten geven aan de crisis-team. In R2 kreeg ik snelle antwoorden. Voor het eerst voelde het als een organisatie die weet wat ze doet. Dank!",
          reliability: "fact",
          senderName: "Medewerker via HR", timestamp: "10:15",
        },
      ],
      roleActions: [
        {
          id: "r5-ceo-boardplan", label: "Concrete verbeter-agenda voor RvC opstellen",
          description: "Top-3 investeringen + eigenaars + deadlines.",
          allowedRoles: ["ceo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Momentum van crisis benutten voor governance-vernieuwing.",
          lessonLearned: "Post-crisis is de enige tijd dat board wél serieus luistert naar IT-investering.",
        },
        {
          id: "r5-ciso-rootcause", label: "Root-cause analyse + control-hardening",
          description: "Waarom stond FS-PROD-01 niet in scope? Concreet plan.",
          allowedRoles: ["ciso"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Blame-free maar concreet. Root cause ≠ blame.",
          lessonLearned: "Ontbrekende MDR-coverage is een detecteerbare fout.",
        },
        {
          id: "r5-it-monitoring", label: "Monitoring uitbreiden — alle prod servers in MDR",
          description: "Contracts-update met Eye Security aanvragen.",
          allowedRoles: ["it_manager"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Feitelijke fix voor de grootste gap.",
          lessonLearned: "MDR-scope is een governance-beslissing, niet IT-technisch.",
        },
        {
          id: "r5-legal-apresponse", label: "AP-vragenlijst voorbereiden — juridisch team",
          description: "14 dagen deadline. Concreet, feitelijk, geen speculatie.",
          allowedRoles: ["legal"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "AP-vervolgonderzoek is standaard bij grote datalek. Bereid voor.",
          lessonLearned: "Vervolgonderzoek is regel, geen uitzondering.",
        },
        {
          id: "r5-cfo-totalcost", label: "Total-cost-of-incident rapportage",
          description: "Direct + indirect + verzekering + boete-risico. RvC input.",
          allowedRoles: ["cfo"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Volledige TCO zichtbaar maakt investering in preventie makkelijker verkocht.",
          lessonLearned: "Onzichtbare kosten (klantvertrek, productiviteit) grootste post.",
        },
        {
          id: "r5-comms-poststorm", label: "Post-storm klantcommunicatie",
          description: "Update naar alle klanten: wat is gebeurd, wat is nu status, wat verandert er.",
          allowedRoles: ["head_of_comms"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Klantvertrouwen wordt in weken herbouwd, niet dagen.",
          lessonLearned: "Post-crisis communicatie is een campagne, niet één statement.",
        },
        {
          id: "r5-hr-recognition", label: "Team-appreciatie + individuele check-ins",
          description: "Individueel gesprek met crisis-team. Debrief én PTSD-risico check.",
          allowedRoles: ["hr_lead"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Crisis-team is uitgeput. HR-follow-up voorkomt burn-out.",
          lessonLearned: "PEOPLE-dimensie: crises hebben menselijke kosten.",
        },
        {
          id: "r5-ops-processchange", label: "Proceswijzigingen doorvoeren op basis van workarounds",
          description: "Welke workaround werkt écht beter dan het oorspronkelijke proces?",
          allowedRoles: ["ops_manager"], irPlanAligned: true, isRecommended: true,
          qualityRank: "best",
          facilitatorCommentary: "Crises leren je waar je processen te ingewikkeld waren.",
          lessonLearned: "BC-workaround wordt soms permanente verbetering.",
        },
        {
          id: "r5-team-nolessons", label: "Vergadering afronden zonder concrete acties",
          description: "'We hebben het goed gedaan' — en verder alles bij het oude laten.",
          allowedRoles: ["ceo", "ciso", "cfo", "legal", "head_of_comms", "hr_lead", "ops_manager", "it_manager"],
          irPlanAligned: false,
          qualityRank: "wrong",
          facilitatorCommentary: "Grootste verliesrisico: geen learning-embedding. Volgende crisis is dezelfde crisis.",
          lessonLearned: "Zonder geformaliseerd learnings-proces herhaalt de crisis zich.",
        },
      ],
      discussionGoal: "Test learning-embedding: worden concrete governance-verbeteringen vastgelegd?",
      keyQuestions: [
        "Welke drie dingen veranderen maandag in het IR-plan?",
        "Wie is eigenaar van elke verandering?",
        "Wat wordt het budget-verhaal richting RvC?",
      ],
      hints: ["Let op teams die naar 'goed gedaan' vluchten zonder concrete acties."],
      expectedDecisions: ["Verbeter-agenda concreet", "Root-cause geïdentificeerd", "AP-respons voorbereid"],
      redFlags: ["Geen concrete follow-up", "Blame-oriented root cause", "Boekje toe zonder investering"],
    },
  ],
  decisions: [
    // Per-round decision after R1: containment vs. continuity axis.
    {
      afterRoundIndex: 0,
      prompt: "Na R1 — containment-koers kiezen",
      perRole: true,
      options: [
        {
          label: "Isolatie van FS-PROD-01 (via netwerk)",
          allowedRole: "ciso",
          outcomeVector: { CONT: 2, FOR: 1, BC: -1, JUR: 0, VER: 0, KOS: 0 },
          qualityRank: "best",
          facilitatorCommentary: "Ideale trade-off: containment + forensiek behouden.",
          lessonLearned: "Isoleren via netwerk = balance tussen indammen en bewijs.",
          leadsTo: "round:1",
        },
        {
          label: "Uitschakelen server (stekker eruit)",
          allowedRole: "it_manager",
          outcomeVector: { CONT: 2, FOR: -2, BC: -2, JUR: 0, VER: 0, KOS: 0 },
          qualityRank: "poor",
          facilitatorCommentary: "Snelle containment maar bewijs weg + BC-impact groter dan nodig.",
          lessonLearned: "Uitzetten = quick fix, forensiek verlies.",
          leadsTo: "round:1",
        },
        {
          label: "Wachten op meer info (30 min)",
          allowedRole: "ceo",
          outcomeVector: { CONT: -2, FOR: 0, BC: 1, JUR: -1, VER: 0, KOS: -1 },
          qualityRank: "wrong",
          facilitatorCommentary: "Half uur is lang voor een actor die al 30 min bezig is.",
          lessonLearned: "Wachten heeft ook een kostenkant.",
          leadsTo: "round:1",
        },
        {
          label: "Geen besluit binnen de tijd",
          implicit: true,
          outcomeVector: { CONT: -2, FOR: -1, BC: -1, JUR: -1, VER: -1, KOS: -1 },
          leadsTo: "round:1",
        },
      ],
    },
    // Per-round decision after R4: pay vs. no-pay.
    {
      afterRoundIndex: 3,
      prompt: "Na R4 — ransom-beslissing",
      perRole: true,
      options: [
        {
          label: "Betalen — 500k via verzekeraar",
          allowedRole: "ceo",
          outcomeVector: { CONT: 0, FOR: 0, BC: 2, JUR: -1, VER: -2, KOS: -2 },
          qualityRank: "poor",
          facilitatorCommentary: "BC-kans hoger maar duidelijke VER + KOS impact.",
          lessonLearned: "Betalen = 30% recidive, 100% VER-impact.",
          leadsTo: "round:4",
        },
        {
          label: "Niet betalen — herstellen via backups",
          allowedRole: "ceo",
          outcomeVector: { CONT: 1, FOR: 1, BC: -1, JUR: 1, VER: 2, KOS: 1 },
          qualityRank: "best",
          facilitatorCommentary: "Principe-standhouden met solide herstel-plan = beste combinatie op lange termijn.",
          lessonLearned: "Non-payment werkt als herstel-plan solide is.",
          leadsTo: "round:4",
        },
        {
          label: "Uitstel — onderhandelaar rekt 24u",
          allowedRole: "cfo",
          outcomeVector: { CONT: 0, FOR: 0, BC: 0, JUR: 0, VER: 1, KOS: 0 },
          qualityRank: "good",
          facilitatorCommentary: "Uitstel = tijd kopen. Nul-som als je die tijd effectief gebruikt.",
          lessonLearned: "Optionaliteit is waarde.",
          leadsTo: "round:4",
        },
        {
          label: "Geen besluit binnen de tijd",
          implicit: true,
          outcomeVector: { CONT: -1, FOR: -1, BC: -2, JUR: -2, VER: -2, KOS: -2 },
          leadsTo: "round:4",
        },
      ],
    },
  ],
  outcomes: [
    {
      key: "voorbeeldig",
      label: "Voorbeeldige respons",
      narrative: "Team escaleerde binnen 15 min, meldde binnen 24u (NCSC) en 48u (AP), koos non-payment met solide herstel-plan. Communicatie transparant, medewerkers eerst geïnformeerd, klanten binnen 6u. Post-crisis: RvC keurt investering in MDR-uitbreiding goed.",
      lessonLearned: "Vroege escalatie + heldere mandaten + transparantie waren doorslaggevend.",
      scoreRange: { min: 8 },
    },
    {
      key: "acceptabel",
      label: "Acceptabel — met verbeter-agenda",
      narrative: "Meldingen op tijd, maar interne communicatie liep achter (medewerkers hoorden het via media). Ransom-besluit was defensibel maar proces was rommelig. AP start vervolgonderzoek — verwachte uitkomst: aanmaning.",
      lessonLearned: "Interne communicatie hoort binnen 4 uur expliciet gepland — anders zakt vertrouwen weg.",
      scoreRange: { min: -3, max: 7 },
    },
    {
      key: "escalerend",
      label: "Escalerende crisis",
      narrative: "Meldplicht gemist (AP-boete waarschijnlijk), betaald zonder herstelkans-check, media-communicatie tegenstrijdig met interne. Reputatie zwaar geraakt — 15% klantverlies binnen 3 maanden.",
      lessonLearned: "Trage besluitvorming + inconsistente communicatie = veelal grotere schade dan het incident zelf.",
      scoreRange: { max: -4 },
    },
  ],
}

export function nis2PolderStormExample(): ScenarioGraph {
  return planToGraph(plan)
}
